AWSTemplateFormatVersion: 2010-09-09
Description: openapi-linter

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  OpenAPILinterDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: makefile

  postLinter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/post-linter.linter
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Process and return lint results from an OpenAPI document.
      Layers:
        - !Ref OpenAPILinterDependenciesLayer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /lint/openapi
            Method: POST
    Metadata:
      BuildMethod: makefile

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
